public class VTS_Address {
    public String extension {get; set;}
    public String city {get;set;}
    public String phone {get; set;}
    public String postalCode {get; set;}
    public String phoneCountryCode {get; set;}
    public String state {get; set;}
    public String address1 {get; set;}
    public String address2 {get; set;}
    public String addressType {get; set;}
    public String address3 {get; set;}
    public String country {get; set;}
        //additional fields BW 7-10  based on new build in VTS
    public string Statename{get;set;}
    public string Countryname {get;set;}
}