public class VTS_TestCenter {
	public Long id {get; set;}
    public String name {get; set;}
    public String version {get; set;}
    public String updateTrack {get; set;}
    public Long lastRMACompleted {get; set;}
    public Long lastUpdate {get; set;}
    public String updateStatus {get; set;}
    public String tedStatus {get; set;}
    public String activeWorkstations {get; set;}
    public String athenaVersion {get; set;}
}